import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import Course from './components/Courses/index';


export const metadata = {
  title: 'AfroBrave',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children} 
        <Footer />
      </body>
    </html>
  )
}
